[package]
authors = []
name    = "ibc-api"
version = "1.0.0"

[addresses]
ibc_api = "_"

[dev-addresses]
ibc_api = "0x9991"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "d34bb3e3dad03241967c0263a6f1fcfe6bccb7d7"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
