[package]
authors = []
name    = "ping-pong"
version = "1.0.0"

[addresses]
ibc       = "_"
ping_pong = "_"

[dev-addresses]
ibc       = "0x2222"
ping_pong = "0x1111"

[dependencies.AptosFramework]
git    = "https://github.com/aeryz/aptos-core.git"
rev    = "d34bb3e3dad03241967c0263a6f1fcfe6bccb7d7"
subdir = "aptos-move/framework/aptos-framework"

[dependencies]
ibc = { local = "../move-ibc" }

[dev-dependencies]
