[package]
edition = "2021"
name    = "voyager-consensus-module-ethereum"
version = "0.1.0"

[dependencies]
beacon-api         = { workspace = true }
bitvec             = { workspace = true }
chain-utils        = { workspace = true }
enumorph           = { workspace = true }
ethereum-verifier  = { workspace = true }
ethers             = { workspace = true, features = ["rustls", "ws"] }
futures            = { workspace = true }
jsonrpsee          = { workspace = true, features = ["macros", "server", "tracing"] }
macros             = { workspace = true }
num-bigint         = { workspace = true }
prost              = { workspace = true }
protos             = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
voyager-vm         = { workspace = true }
