[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "devnet-utils"
repository   = { workspace = true }
version      = "0.1.0"

[lints]
workspace = true

[dependencies]
base64          = { workspace = true }
bip39           = "2.0.0"
clap            = { workspace = true, features = ["derive", "error-context", "help"] }
cosmwasm-std    = "2.0.3"
ed25519-compact = { version = "2.1.1", default-features = false, features = ["ed25519"] }
hex             = { workspace = true, features = ["std"] }
strum           = { version = "0.26.1", features = ["derive"] }
tiny-hderive    = "0.3.0"
unionlabs       = { workspace = true }
